## provide the name of the namespace
namespace:
  name: staging

## define the image to execute with the Deployment 
image:
  tag: 1.18.0

## set the number of replicas for an application 
replicaCount: 1

resources:
  cpu: 50m
  memory: 128Mi
  
configmap:
  data: "version: 1.18.0"